### ISSUE TITLE
kPhonetic for U+3840 㡀

### ISSUE THREAD

**Issue by paulmasson** [unicode-org/unihan-database#90]
This character does not appear in Casey. The closest group would be 1013, where the main phonetic is U+655D 敝, which is this character reclarified with the knock radical. All of the other traditional characters in this group contain this radical, so U+3840 㡀 really doesn't belong.

The are over thirty other characters combining U+3840 㡀 with other radicals, including U+2A406 𪐆 in group 1236. What should be the policy for characters like this that are not in Casey but could constitute new phonetic groups?

We could start a new group 1013A and give all of these additions an asterisk. Any better idea?

**Comment by kenlunde** [comment]
I gave this some thought, and agree that establishing a new group, 1013A, makes the most sense. Anyone with the reference would be able to easily figure out why this pseudo phonetic group was established.

Perhaps related to this, John added to the property syntax in Version 14.0 an optional trailing "+" that was never used in the actual property data, and also was not explained in UAX #38. It remained in Version 15.0, but was removed in Version 15.1. While I am okay simply adding pseudo phonetic groups, perhaps this was the intent for the trailing "+" in the syntax.

If you agree that we should simply add this pseudo phonetic group, please submit a PR accordingly. If you feel that we should be more explicit about this, and restore the optional trailing "+" in the syntax, please submit feedback against [PRI 483](https://www.unicode.org/review/pri483/), which should also include a proposed description of the trailing "+."

**Comment by paulmasson** [comment]
@kenlunde I'm confused as to the point of a trailing plus sign. Any characters not in Casey will be additions: what is the point of distinguishing two types of additions?

Also, are you saying these characters should go in group 1013 with a plus sign instead of an asterisk? I would find that confusing, since the two characters in question don't really share the same phonetic.

One more thought: we could have pseudo phonetic groups be labeled backwards in the alphabet to make them stand out more clearly. In this case the group would be 1013Z. Interesting or not?

**Comment by kenlunde** [comment]
My idea, which was merely speculating what John may have meant for the trailing `+`, would be to use `1013A+` instead of `1013A*`, whereby the `+` would indicate that it is a pseudo phonetic group. Any ideograph assigned to a pseudo phonetic group, of course, would not be in Casey, so the `*` is implied. As to why the use of 1013 as the phonetic group for U+3840, if I were to look for it in Casey, 1013 would be the closest visual match. I looked through the UTC document register, along with the minutes of the UTC meetings that led up to Unicode Version 14.0, but I could find nothing that would indicate why John changed its syntax to allow a trailing `+`.

**Comment by paulmasson** [comment]
@kenlunde I think the simplest thing to do right now is go with the first proposal. Pull request #90 is available for this.
